### PR TITLE
Update dependencies and add update-grayskull bot

### LINKED ISSUE #3: Incorrect dependencies
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

This conda-forge has a number of differences in its dependencies as compared with the [upstream repo](https://github.com/geomstats/geomstats/blob/2.7.0/pyproject.toml).

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

### PR DESCRIPTION
**Pull request by DManowitz**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

Fixes #3

### CODE REVIEW

**Comment by DManowitz** [comment]
@conda-forge-admin, please rerender

**Review by ninamiolane — APPROVED** [review]
LGTM once tests pass.

**Comment by ymontmarin** [comment]
Looks good to me.

I checked the error,  and it looks like the strategy of @luisfpereira https://github.com/geomstats/geomstats/blob/2.7.0/geomstats/_backend/__init__.py that was working in the previous build is not working on this build.

I did not manage to find out why. Maybe it is how conda load files in its tmp folders.. Let us try again in case of

**Comment by ymontmarin** [comment]
@conda-forge-admin, please restart ci

**Comment by ymontmarin** [comment]
@conda-forge-admin, please restart ci

**Comment by ymontmarin** [comment]
Dependencies were updated during the  of the last version: https://github.com/conda-forge/geomstats-feedstock/pull/6

**Pull request closed without merging**
